#!/bin/bash
set -euo pipefail

PI='pi --agent-team-subagent-skills disabled --no-session'
export PI_SKIP_VERSION_CHECK=1

strip_ansi() {
  sed 's/\x1B\[[0-9;?]*[a-zA-Z]//g; s/\x1B\[[<>][0-9;]*[a-zA-Z]//g; s/\x1B[()][0-9A-Za-z]//g'
}

# --- Phase 1: Research + Generate ---
echo '=== Blog Improvement Radar ===' >&2
echo 'Running research and analysis phase...' >&2

RADAR_DATE="$(date +'%B %Y')"
OUTFILE="/tmp/radar-output.md"

printf '%s' "$(cat .pi/prompts/blog-improvement-radar.md)" |
  env PI_CACHE_RETENTION=long timeout 55m $PI --model opencode-go/deepseek-v4-pro 2>&1 |
  strip_ansi |
  tee "$OUTFILE"

echo '' >&2
echo '=== Research complete ===' >&2

# --- Phase 2: Validate output ---
if [[ ! -s "$OUTFILE" ]]; then
  echo 'ERROR: Radar output is empty. Check pi logs above.' >&2
  exit 1
fi

SUGGESTION_COUNT=$(grep -c '^## Suggestion:' "$OUTFILE" || true)
if [[ "$SUGGESTION_COUNT" -eq 0 ]]; then
  echo 'ERROR: No suggestions found in output. Expected format: ## Suggestion: [title]' >&2
  exit 1
fi

echo "Generated ${SUGGESTION_COUNT} suggestions." >&2

# --- Phase 3: Create radar issue ---
echo '=== Creating radar issue ===' >&2

RADAR_TITLE="Blog Improvement Radar — ${RADAR_DATE}"

# Build issue body with metadata footer
ISSUE_BODY="$(cat "$OUTFILE")

---

> 🤖 Generated by [AI Blog Improvement Radar](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/ai-blog-suggestions.yml) on $(date -u +'%Y-%m-%dT%H:%M:%SZ').
> ${SUGGESTION_COUNT} suggestions across 4 domains.
> Approve any suggestion by creating a GitHub issue from it with the \`ai-implement\` label."

# Check if a radar issue for this month already exists
EXISTING_ISSUE=$(gh issue list \
  --search "Blog Improvement Radar — ${RADAR_DATE}" \
  --state open \
  --json number \
  --jq '.[0].number' 2>/dev/null || true)

if [[ -n "$EXISTING_ISSUE" ]]; then
  echo "Radar issue #${EXISTING_ISSUE} already exists for ${RADAR_DATE}. Updating body..." >&2
  gh issue edit "$EXISTING_ISSUE" --body "$ISSUE_BODY"
  ISSUE_NUMBER="$EXISTING_ISSUE"
else
  ISSUE_NUMBER=$(gh issue create \
    --title "$RADAR_TITLE" \
    --body "$ISSUE_BODY" \
    --label 'blog-radar' \
    --json number \
    --jq '.number')

  echo "Created radar issue #${ISSUE_NUMBER}" >&2
fi

echo "issue_number=${ISSUE_NUMBER}" >>"$GITHUB_OUTPUT"
echo "suggestion_count=${SUGGESTION_COUNT}" >>"$GITHUB_OUTPUT"

echo "=== Done ===> https://github.com/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}" >&2
