name: 'Infrastructure Deployment'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'infrastructure/**'

permissions:
  id-token: write
  contents: read

jobs:
  fmt:
    name: 'Terraform Format'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.5

      - name: Terraform Format
        working-directory: ./infrastructure
        run: terraform fmt -check -recursive

  shared:
    name: 'Terraform Shared'
    runs-on: ubuntu-latest
    environment: production
    needs: fmt

    defaults:
      run:
        working-directory: ./infrastructure/stacks/shared

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.AWS_INFRA_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        env:
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="region=eu-west-2"

      - name: Terraform Plan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: terraform plan -input=false -var-file=../../vars/shared/shared.tfvars -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: terraform apply -auto-approve tfplan

  site:
    name: 'Terraform Site (${{ matrix.environment_name }})'
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment_name }}
    needs: shared
    strategy:
      matrix:
        environment_name: [production, staging]

    defaults:
      run:
        working-directory: ./infrastructure/stacks/site

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.AWS_INFRA_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        env:
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          ENVIRONMENT: ${{ matrix.environment_name }}
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="region=eu-west-2" \
            -backend-config="key=site/${ENVIRONMENT}/terraform.tfstate"

      - name: Terraform Plan
        env:
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          ENVIRONMENT: ${{ matrix.environment_name }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: terraform plan -input=false -var="state_bucket=${TF_STATE_BUCKET}" -var-file="../../vars/site/${ENVIRONMENT}.tfvars" -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        env:
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: terraform apply -auto-approve tfplan
